sudo apt-get install libdebuginfod1 -y
sudo apt-get install libxcb-keysyms1 -y
sudo apt-get install libxcb-render-util0 -y
sudo apt-get install libxcb-icccm4 -y
sudo apt-get install libsource-highlight-common -y
sudo apt-get install libc6-dbg:amd64 -y
sudo apt-get install libxcb-image0 -y
sudo apt-get install libc6-x32 -y
sudo apt-get install libxcb-xinerama0 -y
sudo apt-get install qttranslations5-l10n -y
sudo apt-get install libboost-regex1.74.0 -y
sudo apt-get install libipt2 -y
sudo apt-get install libqt5core5a -y
sudo apt-get install libx32gomp1 -y
sudo apt-get install libbabeltrace1 -y
sudo apt-get install libqt5dbus5 -y
sudo apt-get install libmd4c0 -y
sudo apt-get install libc6-i386 -y
sudo apt-get install libx32quadmath0 -y
sudo apt-get install lib32atomic1 -y
sudo apt-get install libsource-highlight4v5 -y
sudo apt-get install libx32atomic1 -y
sudo apt-get install libc6-dev-i386 -y
sudo apt-get install lib32itm1 -y
sudo apt-get install libx32gcc-s1 -y
sudo apt-get install libx32itm1 -y
sudo apt-get install libqt5network5 -y
sudo apt-get install libc6-dev-x32 -y
sudo apt-get install gdb -y
sudo apt-get install lib32gomp1 -y
sudo apt-get install libx32asan6 -y
sudo apt-get install lib32gcc-s1 -y
sudo apt-get install lib32stdc++6 -y
sudo apt-get install lib32asan6 -y
sudo apt-get install lib32quadmath0 -y
sudo apt-get install libx32stdc++6 -y
sudo apt-get install libx32ubsan1 -y
sudo apt-get install libqt5gui5 -y
sudo apt-get install libqt5widgets5 -y
sudo apt-get install lib32ubsan1 -y
sudo apt-get install qt5-gtk-platformtheme -y
sudo apt-get install libx32gcc-11-dev -y
sudo apt-get install lib32gcc-11-dev -y
sudo apt-get install libqt5svg5 -y
sudo apt-get install gcc-11-multilib -y
sudo apt-get install gcc-multilib -y
wget https://download.opensuse.org/repositories/home:/Dman95/Debian_11/amd64/sasm_3.14.0-1_amd64.deb
sudo dpkg -i sasm_3.14.0-1_amd64.deb
rm sasm_3.14.0-1_amd64.deb
